// src/app/profile/[id]/page.tsx
'use client';

import { useParams } from 'next/navigation';
import Header from '@/components/Header';
import ProfilePage from '@/components/ProfilePage';

export default function ProfileRoute() {
  const params = useParams();
  const profileId = params?.id as string;

  if (!profileId) {
    return (
      <div className="min-h-screen tui-bg">
        <Header />
        <main className="mx-auto main-content p-4">
          <p className="text-center tui-text-muted">Loading...</p>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen tui-bg">
      <Header />
      <main className="mx-auto main-content">
        <div className="mx-auto" style={{ maxWidth: '900px' }}>
          <ProfilePage profileId={profileId} />
        </div>
      </main>
    </div>
  );
}

// src/routes/profile/[id]/+page.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import Header from '../../../components/Header.svelte';
  import ProfilePage from '../../../components/ProfilePage.svelte';

  let id = $derived($page.params.id);
</script>

{#if !id}
  <div class="min-h-screen tui-bg">
    <Header />
    <main class="mx-auto main-content p-4">
      <p class="text-center tui-text-muted">Loading...</p>
    </main>
  </div>
{:else}
  <div class="min-h-screen tui-bg">
    <Header />
    <main class="mx-auto main-content">
      <div class="mx-auto" style="max-width: 900px;">
        <ProfilePage profileId={id} />
      </div>
    </main>
  </div>
{/if}
