// src/components/chat-form/ChatForm.svelte
<script lang="ts">
	import { createChatFormContext } from './context.svelte';

	interface Props {
		title: string;
		onSubmit: () => void | Promise<void>;
		onCancel?: () => void;
		submitLabel?: string;
		cancelLabel?: string;
		isValid?: boolean;
		error?: string | null;
		class?: string;
		children: import('svelte').Snippet;
	}

	let {
		title,
		onSubmit,
		onCancel,
		submitLabel = 'Submit',
		cancelLabel = 'Cancel',
		isValid = true,
		error = null,
		class: className = '',
		children
	}: Props = $props();

	const ctx = createChatFormContext();

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (!isValid || ctx.isSubmitting) return;

		ctx.isSubmitting = true;
		try {
			await onSubmit();
		} finally {
			ctx.isSubmitting = false;
		}
	}

	function handleKeyDown(e: KeyboardEvent) {
		// Enter to submit (only if not in a textarea)
		if (e.key === 'Enter' && !e.shiftKey) {
			const target = e.target as HTMLElement;
			if (target.tagName !== 'TEXTAREA') {
				e.preventDefault();
				if (isValid && !ctx.isSubmitting) {
					handleSubmit(new SubmitEvent('submit'));
				}
			}
		}

		// Escape to cancel
		if (e.key === 'Escape' && onCancel) {
			e.preventDefault();
			onCancel();
		}
	}
</script>

<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<form
	onsubmit={handleSubmit}
	onkeydown={handleKeyDown}
	class="chat-form tui-frame {className}"
>
	<!-- Title Bar -->
	<div class="chat-form-title tui-frame-title">
		{title}
	</div>

	<!-- Form Body -->
	<div class="chat-form-body">
		{@render children()}

		<!-- Error Display -->
		{#if error}
			<div class="chat-form-error" role="alert">
				{error}
			</div>
		{/if}
	</div>

	<!-- Footer with Shortcuts -->
	<div class="chat-form-footer">
		<div class="chat-form-shortcuts">
			<span class="chat-form-shortcut">
				<kbd>Tab</kbd> Next
			</span>
			{#if onCancel}
				<span class="chat-form-shortcut">
					<kbd>Esc</kbd> {cancelLabel}
				</span>
			{/if}
			<span class="chat-form-shortcut">
				<kbd>Enter</kbd> {submitLabel}
			</span>
		</div>

		<!-- Action Buttons -->
		<div class="chat-form-actions">
			{#if onCancel}
				<button
					type="button"
					onclick={onCancel}
					class="tui-btn"
					disabled={ctx.isSubmitting}
				>
					{cancelLabel}
				</button>
			{/if}
			<button
				type="submit"
				class="tui-btn chat-form-submit"
				disabled={!isValid || ctx.isSubmitting}
			>
				{ctx.isSubmitting ? 'Saving...' : submitLabel}
			</button>
		</div>
	</div>
</form>

// src/components/chat-form/ChatForm.tsx
'use client';

import React, { type ReactNode, useCallback, type FormEvent } from 'react';
import { ChatFormProvider, useChatForm } from './ChatFormContext';

interface ChatFormProps {
  title: string;
  children: ReactNode;
  onSubmit: () => void | Promise<void>;
  onCancel?: () => void;
  submitLabel?: string;
  cancelLabel?: string;
  isValid?: boolean;
  error?: string | null;
  className?: string;
}

function ChatFormInner({
  title,
  children,
  onSubmit,
  onCancel,
  submitLabel = 'Submit',
  cancelLabel = 'Cancel',
  isValid = true,
  error,
  className = '',
}: ChatFormProps) {
  const { isSubmitting, setIsSubmitting } = useChatForm();

  const handleSubmit = useCallback(async (e: FormEvent) => {
    e.preventDefault();
    if (!isValid || isSubmitting) return;

    setIsSubmitting(true);
    try {
      await onSubmit();
    } finally {
      setIsSubmitting(false);
    }
  }, [isValid, isSubmitting, onSubmit, setIsSubmitting]);

  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    // Enter to submit (only if not in a textarea)
    if (e.key === 'Enter' && !e.shiftKey) {
      const target = e.target as HTMLElement;
      if (target.tagName !== 'TEXTAREA') {
        e.preventDefault();
        if (isValid && !isSubmitting) {
          handleSubmit(e as unknown as FormEvent);
        }
      }
    }

    // Escape to cancel
    if (e.key === 'Escape' && onCancel) {
      e.preventDefault();
      onCancel();
    }
  }, [isValid, isSubmitting, handleSubmit, onCancel]);

  return (
    <form
      onSubmit={handleSubmit}
      onKeyDown={handleKeyDown}
      className={`chat-form tui-frame ${className}`}
      role="form"
    >
      {/* Title Bar */}
      <div className="chat-form-title tui-frame-title">
        {title}
      </div>

      {/* Form Body */}
      <div className="chat-form-body">
        {children}

        {/* Error Display */}
        {error && (
          <div className="chat-form-error" role="alert">
            {error}
          </div>
        )}
      </div>

      {/* Footer with Shortcuts */}
      <div className="chat-form-footer">
        <div className="chat-form-shortcuts">
          <span className="chat-form-shortcut">
            <kbd>Tab</kbd> Next
          </span>
          {onCancel && (
            <span className="chat-form-shortcut">
              <kbd>Esc</kbd> {cancelLabel}
            </span>
          )}
          <span className="chat-form-shortcut">
            <kbd>Enter</kbd> {submitLabel}
          </span>
        </div>

        {/* Action Buttons */}
        <div className="chat-form-actions">
          {onCancel && (
            <button
              type="button"
              onClick={onCancel}
              className="tui-btn"
              disabled={isSubmitting}
            >
              {cancelLabel}
            </button>
          )}
          <button
            type="submit"
            className="tui-btn chat-form-submit"
            disabled={!isValid || isSubmitting}
          >
            {isSubmitting ? 'Saving...' : submitLabel}
          </button>
        </div>
      </div>
    </form>
  );
}

export default function ChatForm(props: ChatFormProps) {
  return (
    <ChatFormProvider onSubmit={props.onSubmit} onCancel={props.onCancel}>
      <ChatFormInner {...props} />
    </ChatFormProvider>
  );
}
