// src/components/BaZiChart.tsx
'use client';

import { useMemo, useState } from 'react';
import PillarCard from './PillarCard';
import { triPillar, PILLARS, COMPARISON, TALISMAN, LOCATION } from '@/lib/t';

interface BaZiChartProps {
  chartData: any;
  showNatal?: boolean;
  show10YrLuck?: boolean;  // Show 10-yr luck with natal pillars
  showLuck?: boolean;       // Show comparison date luck (Annual, Monthly, Daily, Hourly)
  showTalisman?: boolean;
  showLocation?: boolean;
}

// Branch to element mapping
const BRANCH_TO_ELEMENT: Record<string, string> = {
  'Zi': 'Water', 'Chou': 'Earth', 'Yin': 'Wood', 'Mao': 'Wood',
  'Chen': 'Earth', 'Si': 'Fire', 'Wu': 'Fire', 'Wei': 'Earth',
  'Shen': 'Metal', 'You': 'Metal', 'Xu': 'Earth', 'Hai': 'Water'
};

// Stem to element mapping (with yin/yang polarity)
const STEM_TO_ELEMENT: Record<string, { element: string; polarity: 'yang' | 'yin' }> = {
  'Jia': { element: 'Wood', polarity: 'yang' },
  'Yi': { element: 'Wood', polarity: 'yin' },
  'Bing': { element: 'Fire', polarity: 'yang' },
  'Ding': { element: 'Fire', polarity: 'yin' },
  'Wu': { element: 'Earth', polarity: 'yang' },
  'Ji': { element: 'Earth', polarity: 'yin' },
  'Geng': { element: 'Metal', polarity: 'yang' },
  'Xin': { element: 'Metal', polarity: 'yin' },
  'Ren': { element: 'Water', polarity: 'yang' },
  'Gui': { element: 'Water', polarity: 'yin' },
};

// Element to Chinese character
const ELEMENT_CHAR: Record<string, string> = {
  'Wood': '木', 'Fire': '火', 'Earth': '土', 'Metal': '金', 'Water': '水'
};


export default function BaZiChart({
  chartData,
  showNatal = true,
  show10YrLuck = false,
  showLuck = true,
  showTalisman = true,
  showLocation = true
}: BaZiChartProps) {
  const mappings = chartData?.mappings || {};
  const dayMasterStem = chartData?.hs_d?.id || 'Yi';
  const [hoveredInteractionId, setHoveredInteractionId] = useState<string | null>(null);

  // Build pillar data from node
  const buildPillar = (hsKey: string, ebKey: string, label: string, isDayMaster = false) => {
    const hsNode = chartData?.[hsKey];
    const ebNode = chartData?.[ebKey];

    if (!hsNode && !ebNode) return null;

    const stemId = hsNode?.id;
    const branchId = ebNode?.id;

    // Get stem data from API mappings
    const stemMapping = mappings.heavenly_stems?.[stemId] || {};
    const stemInfo = STEM_TO_ELEMENT[stemId];
    const stemElement = stemInfo?.element || 'Unknown';

    const stem = {
      chinese: stemMapping.chinese || stemId || '?',
      element: stemElement,
      color: stemMapping.hex_color  // Just use API hex_color directly
    };

    // Check if branch is pure element transformation
    const isPureElement = ['Fire', 'Water', 'Metal', 'Wood', 'Earth'].includes(branchId);

    let branch;
    if (isPureElement) {
      // Pure element transformation - use element hex_color from API
      branch = {
        chinese: ELEMENT_CHAR[branchId] || branchId,
        animal: branchId,
        element: branchId,
        color: mappings.elements?.[branchId]?.hex_color  // Just use API hex_color directly
      };
    } else {
      // Normal branch - use branch hex_color from API
      const branchMapping = mappings.earthly_branches?.[branchId] || {};
      const branchElement = BRANCH_TO_ELEMENT[branchId] || 'Unknown';
      branch = {
        chinese: branchMapping.chinese || branchId || '?',
        animal: branchMapping.animal || '?',
        element: branchElement,
        color: branchMapping.hex_color  // Just use API hex_color directly
      };
    }

    // Get hidden stems (qi) data - use base_qi only (original branch composition)
    const baseQi = ebNode?.base_qi && Object.keys(ebNode.base_qi).length > 0
      ? ebNode.base_qi : null;
    const hiddenQi = baseQi || {};

    // Map hidden stems to Ten Gods
    const hiddenStems: Record<string, string> = {};
    if (hiddenQi && mappings.ten_gods) {
      for (const stemName of Object.keys(hiddenQi)) {
        const tenGodData = mappings.ten_gods?.[dayMasterStem]?.[stemName];
        hiddenStems[stemName] = tenGodData?.abbreviation || tenGodData?.id || '';
      }
    }

    // Get Ten God for stem
    let tenGod = null;
    if (isDayMaster) {
      tenGod = 'DM';
    } else if (stemId && mappings.ten_gods) {
      const tenGodData = mappings.ten_gods?.[dayMasterStem]?.[stemId];
      tenGod = tenGodData?.abbreviation || tenGodData?.id || null;
    }

    // Get badges
    const stemBadges = hsNode?.badges || [];
    const branchBadges = ebNode?.badges || [];

    return {
      label,
      stem,
      stemName: stemId,
      branch,
      branchName: branchId,
      stemKey: hsKey,
      branchKey: ebKey,
      hiddenStems,
      hiddenQi,
      tenGod,
      isDayMaster,
      isUnknown: !hsNode && !ebNode,
      qiPhase: hsNode?.qi_phase || ebNode?.qi_phase || null,
      qiPhaseAnalysis: undefined as any,  // populated after build for natal pillars
      stemTransformations: stemBadges.filter((b: any) => b.type === 'transformation'),
      branchTransformations: branchBadges.filter((b: any) => b.type === 'transformation'),
      stemCombinations: stemBadges.filter((b: any) => b.type === 'combination'),
      branchCombinations: branchBadges.filter((b: any) => b.type === 'combination'),
      stemNegatives: stemBadges.filter((b: any) =>
        ['clash', 'harm', 'punishment', 'destruction', 'stem_conflict'].includes(b.type)),
      branchNegatives: branchBadges.filter((b: any) =>
        ['clash', 'harm', 'punishment', 'destruction', 'stem_conflict'].includes(b.type)),
      branchWealthStorage: branchBadges.filter((b: any) => b.type === 'wealth_storage'),
    };
  };

  // Build natal pillars
  const natalPillars = useMemo(() => {
    const hour = buildPillar('hs_h', 'eb_h', triPillar(PILLARS.hour)) || {
      label: triPillar(PILLARS.hour),
      stem: { chinese: '?', element: 'Unknown', color: '' },
      stemName: '?',
      branch: { chinese: '?', animal: '?', element: 'Unknown', color: '' },
      branchName: '?',
      hiddenStems: {},
      hiddenQi: {},
      tenGod: null,
      isDayMaster: false,
      isUnknown: true,
      qiPhaseAnalysis: undefined as any,
      stemTransformations: [],
      branchTransformations: [],
      stemCombinations: [],
      branchCombinations: [],
      stemNegatives: [],
      branchNegatives: [],
      branchWealthStorage: [],
    };
    const day = buildPillar('hs_d', 'eb_d', triPillar(PILLARS.day), true);
    const month = buildPillar('hs_m', 'eb_m', triPillar(PILLARS.month));
    const year = buildPillar('hs_y', 'eb_y', triPillar(PILLARS.year));

    // Attach qi phase analysis to natal pillars
    const qiPhaseData = chartData?.qi_phase_analysis?.pillars;
    const pillarPositionMap: Record<number, string> = { 0: 'hour', 1: 'day', 2: 'month', 3: 'year' };
    const result = [hour, day, month, year];
    if (qiPhaseData) {
      result.forEach((pillar, idx) => {
        if (pillar) {
          const posKey = pillarPositionMap[idx];
          pillar.qiPhaseAnalysis = qiPhaseData[posKey] || undefined;
        }
      });
    }

    return result.filter(Boolean) as any[];
  }, [chartData]);

  // Empty placeholder pillar for alignment
  const createEmptyPillar = (label: string) => ({
    label,
    stem: { chinese: '', element: 'Unknown', color: '' },
    stemName: '',
    branch: { chinese: '', animal: '', element: 'Unknown', color: '' },
    branchName: '',
    hiddenStems: {},
    hiddenQi: {},
    tenGod: null,
    isDayMaster: false,
    isUnknown: true,
    isEmpty: true,
    stemTransformations: [],
    branchTransformations: [],
    stemCombinations: [],
    branchCombinations: [],
    stemNegatives: [],
    branchNegatives: [],
    branchWealthStorage: [],
  });

  // Build aligned comparison row: Hourly | Daily | Monthly | Annual | 10-Yr Luck
  // Order matches natal: Hour | Day | Month | Year | (extra column)
  const alignedLuckPillars = useMemo(() => {
    // Hourly luck (aligns with Hour)
    let hourlyPillar = createEmptyPillar(triPillar(COMPARISON.hourly));
    if (chartData?.analysis_info?.has_hourly && chartData?.hs_hl && chartData?.eb_hl) {
      const pillar = buildPillar('hs_hl', 'eb_hl', triPillar(COMPARISON.hourly)) as any;
      if (pillar) {
        pillar.isHourlyLuck = true;
        hourlyPillar = pillar;
      }
    }

    // Daily luck (aligns with Day)
    let dailyPillar = createEmptyPillar(triPillar(COMPARISON.daily));
    if (chartData?.analysis_info?.has_daily && chartData?.hs_dl && chartData?.eb_dl) {
      const pillar = buildPillar('hs_dl', 'eb_dl', triPillar(COMPARISON.daily)) as any;
      if (pillar) {
        pillar.isDailyLuck = true;
        dailyPillar = pillar;
      }
    }

    // Monthly luck (aligns with Month)
    let monthlyPillar = createEmptyPillar(triPillar(COMPARISON.monthly));
    if (chartData?.analysis_info?.has_monthly && chartData?.hs_ml && chartData?.eb_ml) {
      const pillar = buildPillar('hs_ml', 'eb_ml', triPillar(COMPARISON.monthly)) as any;
      if (pillar) {
        pillar.isMonthlyLuck = true;
        monthlyPillar = pillar;
      }
    }

    // Annual luck (aligns with Year)
    let annualPillar = createEmptyPillar(triPillar(COMPARISON.annual));
    if (chartData?.analysis_info?.year && chartData?.hs_yl && chartData?.eb_yl) {
      const pillar = buildPillar('hs_yl', 'eb_yl', triPillar(COMPARISON.annual)) as any;
      if (pillar) {
        pillar.isAnnualLuck = true;
        pillar.year = chartData.analysis_info.year;
        annualPillar = pillar;
      }
    }

    // 10-Yr luck (rightmost column)
    let tenYrPillar = createEmptyPillar(triPillar(COMPARISON.ten_year));
    if (chartData?.analysis_info?.has_luck_pillar && chartData?.hs_10yl && chartData?.eb_10yl) {
      const pillar = buildPillar('hs_10yl', 'eb_10yl', triPillar(COMPARISON.ten_year)) as any;
      if (pillar) {
        pillar.isLuckPillar = true;
        pillar.is10YrLuck = true;
        const misc = chartData.hs_10yl?.misc || chartData.eb_10yl?.misc;
        if (misc) {
          pillar.timing = {
            start_year: parseInt(misc.start_date?.split('-')[0] || '0'),
            end_year: parseInt(misc.end_date?.split('-')[0] || '0'),
            start_age: misc.start_age || 0,
            end_age: misc.end_age || 10,
          };
        }
        tenYrPillar = pillar;
      }
    }

    return [hourlyPillar, dailyPillar, monthlyPillar, annualPillar, tenYrPillar];
  }, [chartData]);

  // Build comparison date luck pillars (legacy - keep for backward compatibility)
  const luckPillars = useMemo(() => {
    const pillars: any[] = [];

    // Annual luck pillar
    if (chartData?.analysis_info?.year && chartData?.hs_yl && chartData?.eb_yl) {
      const pillar = buildPillar('hs_yl', 'eb_yl', 'Annual 年運') as any;
      if (pillar) {
        pillar.isAnnualLuck = true;
        pillar.year = chartData.analysis_info.year;
        pillars.push(pillar);
      }
    }

    // Monthly luck pillar
    if (chartData?.analysis_info?.has_monthly && chartData?.hs_ml && chartData?.eb_ml) {
      const pillar = buildPillar('hs_ml', 'eb_ml', 'Monthly 月運') as any;
      if (pillar) {
        pillar.isMonthlyLuck = true;
        pillars.push(pillar);
      }
    }

    // Daily luck pillar
    if (chartData?.analysis_info?.has_daily && chartData?.hs_dl && chartData?.eb_dl) {
      const pillar = buildPillar('hs_dl', 'eb_dl', 'Daily 日運') as any;
      if (pillar) {
        pillar.isDailyLuck = true;
        pillars.push(pillar);
      }
    }

    // Hourly luck pillar
    if (chartData?.analysis_info?.has_hourly && chartData?.hs_hl && chartData?.eb_hl) {
      const pillar = buildPillar('hs_hl', 'eb_hl', 'Hourly 時運') as any;
      if (pillar) {
        pillar.isHourlyLuck = true;
        pillars.push(pillar);
      }
    }

    return pillars;
  }, [chartData]);

  // Build talisman pillars
  const talismanPillars = useMemo(() => {
    const pillars: any[] = [];

    // Talisman Year
    if (chartData?.hs_ty || chartData?.eb_ty) {
      const pillar = buildPillar('hs_ty', 'eb_ty', triPillar(TALISMAN.year)) as any;
      if (pillar) {
        pillar.isTalisman = true;
        pillar.isTalismanYear = true;
        pillars.push(pillar);
      }
    }

    // Talisman Month
    if (chartData?.hs_tm || chartData?.eb_tm) {
      const pillar = buildPillar('hs_tm', 'eb_tm', triPillar(TALISMAN.month)) as any;
      if (pillar) {
        pillar.isTalisman = true;
        pillar.isTalismanMonth = true;
        pillars.push(pillar);
      }
    }

    // Talisman Day
    if (chartData?.hs_td || chartData?.eb_td) {
      const pillar = buildPillar('hs_td', 'eb_td', triPillar(TALISMAN.day)) as any;
      if (pillar) {
        pillar.isTalisman = true;
        pillar.isTalismanDay = true;
        pillars.push(pillar);
      }
    }

    // Talisman Hour
    if (chartData?.hs_th || chartData?.eb_th) {
      const pillar = buildPillar('hs_th', 'eb_th', triPillar(TALISMAN.hour)) as any;
      if (pillar) {
        pillar.isTalisman = true;
        pillar.isTalismanHour = true;
        pillars.push(pillar);
      }
    }

    return pillars;
  }, [chartData]);

  // Build location pillars (overseas or birthplace)
  const locationPillars = useMemo(() => {
    const pillars: any[] = [];

    // Overseas pillars (o1, o2) - blue border
    if (chartData?.hs_o1 || chartData?.eb_o1) {
      const pillar = buildPillar('hs_o1', 'eb_o1', triPillar(LOCATION.overseas_1)) as any;
      if (pillar) {
        pillar.isLocation = true;
        pillar.isOverseas = true;
        pillars.push(pillar);
      }
    }
    if (chartData?.hs_o2 || chartData?.eb_o2) {
      const pillar = buildPillar('hs_o2', 'eb_o2', triPillar(LOCATION.overseas_2)) as any;
      if (pillar) {
        pillar.isLocation = true;
        pillar.isOverseas = true;
        pillars.push(pillar);
      }
    }

    // Birthplace pillars (b1-b4) - amber border
    if (chartData?.hs_b1 || chartData?.eb_b1) {
      const pillar = buildPillar('hs_b1', 'eb_b1', triPillar(LOCATION.birthplace_1)) as any;
      if (pillar) {
        pillar.isLocation = true;
        pillar.isBirthplace = true;
        pillars.push(pillar);
      }
    }
    if (chartData?.hs_b2 || chartData?.eb_b2) {
      const pillar = buildPillar('hs_b2', 'eb_b2', triPillar(LOCATION.birthplace_2)) as any;
      if (pillar) {
        pillar.isLocation = true;
        pillar.isBirthplace = true;
        pillars.push(pillar);
      }
    }
    if (chartData?.hs_b3 || chartData?.eb_b3) {
      const pillar = buildPillar('hs_b3', 'eb_b3', triPillar(LOCATION.birthplace_3)) as any;
      if (pillar) {
        pillar.isLocation = true;
        pillar.isBirthplace = true;
        pillars.push(pillar);
      }
    }
    if (chartData?.hs_b4 || chartData?.eb_b4) {
      const pillar = buildPillar('hs_b4', 'eb_b4', triPillar(LOCATION.birthplace_4)) as any;
      if (pillar) {
        pillar.isLocation = true;
        pillar.isBirthplace = true;
        pillars.push(pillar);
      }
    }

    return pillars;
  }, [chartData]);

  // Filter pillars based on props
  const displayNatalPillars = showNatal ? natalPillars : [];

  // Use aligned luck pillars when showing comparison row (includes 10-yr luck at the end)
  const displayAlignedLuckPillars = (showLuck || show10YrLuck) ? alignedLuckPillars : [];

  const displayTalismanPillars = showTalisman ? talismanPillars : [];
  const displayLocationPillars = showLocation ? locationPillars : [];

  // Calculate cumulative indices for proper ordering
  const natalOffset = 0;
  const luckOffset = displayNatalPillars.length;
  const talismanOffset = luckOffset + displayAlignedLuckPillars.length;
  const locationOffset = talismanOffset + displayTalismanPillars.length;

  // Check if any pillars to display
  const hasPillars = displayNatalPillars.length > 0 || displayAlignedLuckPillars.length > 0 ||
    displayTalismanPillars.length > 0 || displayLocationPillars.length > 0;

  if (!hasPillars) return null;

  return (
    <div className="relative">
      <div className="relative w-full">
        {/* Heavenly Stems Row */}
        <div className="flex gap-0 items-center flex-wrap">
          {/* Natal Pillar Stems */}
          {displayNatalPillars.map((pillar, index) => (
            <PillarCard
              key={`stem-${index}`}
              pillar={pillar}
              type="stem"
              index={natalOffset + index}
              mappings={mappings}
              hoveredInteractionId={hoveredInteractionId}
              onHoverInteraction={setHoveredInteractionId}
            />
          ))}

          {/* Aligned Luck Pillar Stems: Hourly | Daily | Monthly | Annual | 10-Yr */}
          {displayAlignedLuckPillars.map((pillar, index) => (
            <PillarCard
              key={`luck-stem-${index}`}
              pillar={pillar}
              type="stem"
              index={luckOffset + index}
              mappings={mappings}
              isLuck
              isEmpty={pillar.isEmpty}
              hoveredInteractionId={hoveredInteractionId}
              onHoverInteraction={setHoveredInteractionId}
            />
          ))}

          {/* Divider before location pillars */}
          {displayAlignedLuckPillars.length > 0 && displayLocationPillars.length > 0 && (
            <div className={`luck-divider self-stretch bg-gradient-to-b from-transparent to-transparent opacity-70 ${
              displayLocationPillars[0]?.isOverseas ? 'via-blue-500' : 'via-amber-500'
            }`}></div>
          )}

          {/* Location Pillar Stems */}
          {displayLocationPillars.map((pillar, index) => (
            <PillarCard
              key={`location-stem-${index}`}
              pillar={pillar}
              type="stem"
              index={locationOffset + index}
              mappings={mappings}
              isLocation
              isOverseas={pillar.isOverseas}
              isBirthplace={pillar.isBirthplace}
              hoveredInteractionId={hoveredInteractionId}
              onHoverInteraction={setHoveredInteractionId}
            />
          ))}

          {/* Talisman Pillar Stems */}
          {displayTalismanPillars.map((pillar, index) => (
            <PillarCard
              key={`talisman-stem-${index}`}
              pillar={pillar}
              type="stem"
              index={talismanOffset + index}
              mappings={mappings}
              isTalisman
              hoveredInteractionId={hoveredInteractionId}
              onHoverInteraction={setHoveredInteractionId}
            />
          ))}
        </div>

        {/* Dong Gong indicator row - between HS and EB on daily luck pillar */}
        {chartData?.dong_gong?.rating && displayAlignedLuckPillars.length > 0 && (
          <div className="flex gap-0 items-center">
            {/* Empty spacers for natal pillars */}
            {displayNatalPillars.map((_, index) => (
              <div key={`dg-natal-${index}`} className="w-28 flex-shrink-0" />
            ))}
            {/* Luck pillar columns - only daily (index 1) shows badge */}
            {displayAlignedLuckPillars.map((_, index) => (
              <div key={`dg-luck-${index}`} className="w-28 flex-shrink-0 flex items-center justify-center">
                {index === 1 && (
                  <span
                    className="text-xs font-medium px-1.5"
                    style={{
                      color: chartData.dong_gong.rating.value >= 4 ? 'var(--tui-wood)'
                        : chartData.dong_gong.rating.value === 3 ? 'var(--tui-earth)'
                        : chartData.dong_gong.rating.value === 2.5 ? 'var(--tui-water)'
                        : chartData.dong_gong.rating.value <= 1 ? '#000000'
                        : 'var(--tui-fire)',
                    }}
                    title={
                      chartData.dong_gong.forbidden
                        ? `董公: ${chartData.dong_gong.forbidden.chinese} (${chartData.dong_gong.forbidden.solar_term_chinese}) — ${chartData.dong_gong.forbidden.english}`
                        : chartData.dong_gong.consult?.promoted
                        ? `董公: ${chartData.dong_gong.officer?.chinese || ''} 議 (originally 凶) — ${chartData.dong_gong.consult.reason}`
                        : `董公: ${chartData.dong_gong.officer?.chinese || ''} ${chartData.dong_gong.rating.chinese}`
                    }
                  >
                    {chartData.dong_gong.rating.symbol} {chartData.dong_gong.rating.chinese}
                  </span>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Earthly Branches Row */}
        <div className="flex gap-0 overflow-visible items-stretch">
          {/* Natal Pillar Branches */}
          {displayNatalPillars.map((pillar, index) => (
            <PillarCard
              key={`branch-${index}`}
              pillar={pillar}
              type="branch"
              index={natalOffset + index}
              mappings={mappings}
              hoveredInteractionId={hoveredInteractionId}
              onHoverInteraction={setHoveredInteractionId}
            />
          ))}

          {/* Aligned Luck Pillar Branches: Hourly | Daily | Monthly | Annual | 10-Yr */}
          {displayAlignedLuckPillars.map((pillar, index) => (
            <PillarCard
              key={`luck-branch-${index}`}
              pillar={pillar}
              type="branch"
              index={luckOffset + index}
              mappings={mappings}
              isLuck
              isEmpty={pillar.isEmpty}
              hoveredInteractionId={hoveredInteractionId}
              onHoverInteraction={setHoveredInteractionId}
            />
          ))}

          {/* Divider before location pillars */}
          {displayAlignedLuckPillars.length > 0 && displayLocationPillars.length > 0 && (
            <div className={`luck-divider self-stretch bg-gradient-to-b from-transparent to-transparent opacity-70 ${
              displayLocationPillars[0]?.isOverseas ? 'via-blue-500' : 'via-amber-500'
            }`}></div>
          )}

          {/* Location Pillar Branches */}
          {displayLocationPillars.map((pillar, index) => (
            <PillarCard
              key={`location-branch-${index}`}
              pillar={pillar}
              type="branch"
              index={locationOffset + index}
              mappings={mappings}
              isLocation
              isOverseas={pillar.isOverseas}
              isBirthplace={pillar.isBirthplace}
              hoveredInteractionId={hoveredInteractionId}
              onHoverInteraction={setHoveredInteractionId}
            />
          ))}

          {/* Talisman Pillar Branches */}
          {displayTalismanPillars.map((pillar, index) => (
            <PillarCard
              key={`talisman-branch-${index}`}
              pillar={pillar}
              type="branch"
              index={talismanOffset + index}
              mappings={mappings}
              isTalisman
              hoveredInteractionId={hoveredInteractionId}
              onHoverInteraction={setHoveredInteractionId}
            />
          ))}
        </div>
      </div>
    </div>
  );
}

// src/components/BaZiChart.svelte
<script lang="ts">
  import PillarCard from './PillarCard.svelte';

  interface BaZiChartProps {
    chartData: any;
    showNatal?: boolean;
    show10YrLuck?: boolean;
    showLuck?: boolean;
    showTalisman?: boolean;
    showLocation?: boolean;
  }

  let {
    chartData,
    showNatal = true,
    show10YrLuck = false,
    showLuck = true,
    showTalisman = true,
    showLocation = true,
  }: BaZiChartProps = $props();

  // Branch to element mapping
  const BRANCH_TO_ELEMENT: Record<string, string> = {
    'Zi': 'Water', 'Chou': 'Earth', 'Yin': 'Wood', 'Mao': 'Wood',
    'Chen': 'Earth', 'Si': 'Fire', 'Wu': 'Fire', 'Wei': 'Earth',
    'Shen': 'Metal', 'You': 'Metal', 'Xu': 'Earth', 'Hai': 'Water',
  };

  // Stem to element mapping (with yin/yang polarity)
  const STEM_TO_ELEMENT: Record<string, { element: string; polarity: 'yang' | 'yin' }> = {
    'Jia': { element: 'Wood', polarity: 'yang' },
    'Yi': { element: 'Wood', polarity: 'yin' },
    'Bing': { element: 'Fire', polarity: 'yang' },
    'Ding': { element: 'Fire', polarity: 'yin' },
    'Wu': { element: 'Earth', polarity: 'yang' },
    'Ji': { element: 'Earth', polarity: 'yin' },
    'Geng': { element: 'Metal', polarity: 'yang' },
    'Xin': { element: 'Metal', polarity: 'yin' },
    'Ren': { element: 'Water', polarity: 'yang' },
    'Gui': { element: 'Water', polarity: 'yin' },
  };

  // Element to Chinese character
  const ELEMENT_CHAR: Record<string, string> = {
    'Wood': '\u6728', 'Fire': '\u706B', 'Earth': '\u571F', 'Metal': '\u91D1', 'Water': '\u6C34',
  };

  let mappings = $derived(chartData?.mappings || {});
  let dayMasterStem = $derived(chartData?.hs_d?.id || 'Yi');
  let hoveredInteractionId = $state<string | null>(null);

  // Build pillar data from node
  function buildPillar(hsKey: string, ebKey: string, label: string, isDayMaster = false) {
    const hsNode = chartData?.[hsKey];
    const ebNode = chartData?.[ebKey];

    if (!hsNode && !ebNode) return null;

    const stemId = hsNode?.id;
    const branchId = ebNode?.id;

    // Get stem data from API mappings
    const stemMapping = mappings.heavenly_stems?.[stemId] || {};
    const stemInfo = STEM_TO_ELEMENT[stemId];
    const stemElement = stemInfo?.element || 'Unknown';

    const stem = {
      chinese: stemMapping.chinese || stemId || '?',
      element: stemElement,
      color: stemMapping.hex_color,
    };

    // Check if branch is pure element transformation
    const isPureElement = ['Fire', 'Water', 'Metal', 'Wood', 'Earth'].includes(branchId);

    let branch;
    if (isPureElement) {
      branch = {
        chinese: ELEMENT_CHAR[branchId] || branchId,
        animal: branchId,
        element: branchId,
        color: mappings.elements?.[branchId]?.hex_color,
      };
    } else {
      const branchMapping = mappings.earthly_branches?.[branchId] || {};
      const branchElement = BRANCH_TO_ELEMENT[branchId] || 'Unknown';
      branch = {
        chinese: branchMapping.chinese || branchId || '?',
        animal: branchMapping.animal || '?',
        element: branchElement,
        color: branchMapping.hex_color,
      };
    }

    // Get hidden stems (qi) data - use base_qi only
    const baseQi = ebNode?.base_qi && Object.keys(ebNode.base_qi).length > 0
      ? ebNode.base_qi : null;
    const hiddenQi = baseQi || {};

    // Map hidden stems to Ten Gods
    const hiddenStems: Record<string, string> = {};
    if (hiddenQi && mappings.ten_gods) {
      for (const stemName of Object.keys(hiddenQi)) {
        const tenGodData = mappings.ten_gods?.[dayMasterStem]?.[stemName];
        hiddenStems[stemName] = tenGodData?.abbreviation || tenGodData?.id || '';
      }
    }

    // Get Ten God for stem
    let tenGod = null;
    if (isDayMaster) {
      tenGod = 'DM';
    } else if (stemId && mappings.ten_gods) {
      const tenGodData = mappings.ten_gods?.[dayMasterStem]?.[stemId];
      tenGod = tenGodData?.abbreviation || tenGodData?.id || null;
    }

    // Get badges
    const stemBadges = hsNode?.badges || [];
    const branchBadges = ebNode?.badges || [];

    return {
      label,
      stem,
      stemName: stemId,
      branch,
      branchName: branchId,
      stemKey: hsKey,
      branchKey: ebKey,
      hiddenStems,
      hiddenQi,
      tenGod,
      isDayMaster,
      isUnknown: !hsNode && !ebNode,
      qiPhase: hsNode?.qi_phase || ebNode?.qi_phase || null,
      qiPhaseAnalysis: undefined as any,
      stemTransformations: stemBadges.filter((b: any) => b.type === 'transformation'),
      branchTransformations: branchBadges.filter((b: any) => b.type === 'transformation'),
      stemCombinations: stemBadges.filter((b: any) => b.type === 'combination'),
      branchCombinations: branchBadges.filter((b: any) => b.type === 'combination'),
      stemNegatives: stemBadges.filter((b: any) =>
        ['clash', 'harm', 'punishment', 'destruction', 'stem_conflict'].includes(b.type)),
      branchNegatives: branchBadges.filter((b: any) =>
        ['clash', 'harm', 'punishment', 'destruction', 'stem_conflict'].includes(b.type)),
      branchWealthStorage: branchBadges.filter((b: any) => b.type === 'wealth_storage'),
    };
  }

  // Empty placeholder pillar for alignment
  function createEmptyPillar(label: string) {
    return {
      label,
      stem: { chinese: '', element: 'Unknown', color: '' },
      stemName: '',
      branch: { chinese: '', animal: '', element: 'Unknown', color: '' },
      branchName: '',
      hiddenStems: {},
      hiddenQi: {},
      tenGod: null,
      isDayMaster: false,
      isUnknown: true,
      isEmpty: true,
      stemTransformations: [],
      branchTransformations: [],
      stemCombinations: [],
      branchCombinations: [],
      stemNegatives: [],
      branchNegatives: [],
      branchWealthStorage: [],
    };
  }

  // Build natal pillars
  let natalPillars = $derived.by(() => {
    const hour = buildPillar('hs_h', 'eb_h', 'Hour \u6642') || {
      label: 'Hour \u6642',
      stem: { chinese: '?', element: 'Unknown', color: '' },
      stemName: '?',
      branch: { chinese: '?', animal: '?', element: 'Unknown', color: '' },
      branchName: '?',
      hiddenStems: {},
      hiddenQi: {},
      tenGod: null,
      isDayMaster: false,
      isUnknown: true,
      qiPhaseAnalysis: undefined as any,
      stemTransformations: [],
      branchTransformations: [],
      stemCombinations: [],
      branchCombinations: [],
      stemNegatives: [],
      branchNegatives: [],
      branchWealthStorage: [],
    };
    const day = buildPillar('hs_d', 'eb_d', 'Day \u65E5', true);
    const month = buildPillar('hs_m', 'eb_m', 'Month \u6708');
    const year = buildPillar('hs_y', 'eb_y', 'Year \u5E74');

    // Attach qi phase analysis to natal pillars
    const qiPhaseData = chartData?.qi_phase_analysis?.pillars;
    const pillarPositionMap: Record<number, string> = { 0: 'hour', 1: 'day', 2: 'month', 3: 'year' };
    const result = [hour, day, month, year];
    if (qiPhaseData) {
      result.forEach((pillar, idx) => {
        if (pillar) {
          const posKey = pillarPositionMap[idx];
          (pillar as any).qiPhaseAnalysis = qiPhaseData[posKey] || undefined;
        }
      });
    }

    return result.filter(Boolean) as any[];
  });

  // Build aligned comparison row: Hourly | Daily | Monthly | Annual | 10-Yr Luck
  let alignedLuckPillars = $derived.by(() => {
    // Hourly luck (aligns with Hour)
    let hourlyPillar: any = createEmptyPillar('Hourly \u6642\u904B');
    if (chartData?.analysis_info?.has_hourly && chartData?.hs_hl && chartData?.eb_hl) {
      const pillar = buildPillar('hs_hl', 'eb_hl', 'Hourly \u6642\u904B') as any;
      if (pillar) {
        pillar.isHourlyLuck = true;
        hourlyPillar = pillar;
      }
    }

    // Daily luck (aligns with Day)
    let dailyPillar: any = createEmptyPillar('Daily \u65E5\u904B');
    if (chartData?.analysis_info?.has_daily && chartData?.hs_dl && chartData?.eb_dl) {
      const pillar = buildPillar('hs_dl', 'eb_dl', 'Daily \u65E5\u904B') as any;
      if (pillar) {
        pillar.isDailyLuck = true;
        dailyPillar = pillar;
      }
    }

    // Monthly luck (aligns with Month)
    let monthlyPillar: any = createEmptyPillar('Monthly \u6708\u904B');
    if (chartData?.analysis_info?.has_monthly && chartData?.hs_ml && chartData?.eb_ml) {
      const pillar = buildPillar('hs_ml', 'eb_ml', 'Monthly \u6708\u904B') as any;
      if (pillar) {
        pillar.isMonthlyLuck = true;
        monthlyPillar = pillar;
      }
    }

    // Annual luck (aligns with Year)
    let annualPillar: any = createEmptyPillar('Annual \u5E74\u904B');
    if (chartData?.analysis_info?.year && chartData?.hs_yl && chartData?.eb_yl) {
      const pillar = buildPillar('hs_yl', 'eb_yl', 'Annual \u5E74\u904B') as any;
      if (pillar) {
        pillar.isAnnualLuck = true;
        pillar.year = chartData.analysis_info.year;
        annualPillar = pillar;
      }
    }

    // 10-Yr luck (rightmost column)
    let tenYrPillar: any = createEmptyPillar('10-Yr \u5927\u904B');
    if (chartData?.analysis_info?.has_luck_pillar && chartData?.hs_10yl && chartData?.eb_10yl) {
      const pillar = buildPillar('hs_10yl', 'eb_10yl', '10-Yr \u5927\u904B') as any;
      if (pillar) {
        pillar.isLuckPillar = true;
        pillar.is10YrLuck = true;
        const misc = chartData.hs_10yl?.misc || chartData.eb_10yl?.misc;
        if (misc) {
          pillar.timing = {
            start_year: parseInt(misc.start_date?.split('-')[0] || '0'),
            end_year: parseInt(misc.end_date?.split('-')[0] || '0'),
            start_age: misc.start_age || 0,
            end_age: misc.end_age || 10,
          };
        }
        tenYrPillar = pillar;
      }
    }

    return [hourlyPillar, dailyPillar, monthlyPillar, annualPillar, tenYrPillar];
  });

  // Build talisman pillars
  let talismanPillars = $derived.by(() => {
    const pillars: any[] = [];

    if (chartData?.hs_ty || chartData?.eb_ty) {
      const pillar = buildPillar('hs_ty', 'eb_ty', 'T Year') as any;
      if (pillar) { pillar.isTalisman = true; pillar.isTalismanYear = true; pillars.push(pillar); }
    }
    if (chartData?.hs_tm || chartData?.eb_tm) {
      const pillar = buildPillar('hs_tm', 'eb_tm', 'T Month') as any;
      if (pillar) { pillar.isTalisman = true; pillar.isTalismanMonth = true; pillars.push(pillar); }
    }
    if (chartData?.hs_td || chartData?.eb_td) {
      const pillar = buildPillar('hs_td', 'eb_td', 'T Day') as any;
      if (pillar) { pillar.isTalisman = true; pillar.isTalismanDay = true; pillars.push(pillar); }
    }
    if (chartData?.hs_th || chartData?.eb_th) {
      const pillar = buildPillar('hs_th', 'eb_th', 'T Hour') as any;
      if (pillar) { pillar.isTalisman = true; pillar.isTalismanHour = true; pillars.push(pillar); }
    }

    return pillars;
  });

  // Build location pillars (overseas or birthplace)
  let locationPillars = $derived.by(() => {
    const pillars: any[] = [];

    // Overseas pillars (o1, o2)
    if (chartData?.hs_o1 || chartData?.eb_o1) {
      const pillar = buildPillar('hs_o1', 'eb_o1', 'Overseas 1') as any;
      if (pillar) { pillar.isLocation = true; pillar.isOverseas = true; pillars.push(pillar); }
    }
    if (chartData?.hs_o2 || chartData?.eb_o2) {
      const pillar = buildPillar('hs_o2', 'eb_o2', 'Overseas 2') as any;
      if (pillar) { pillar.isLocation = true; pillar.isOverseas = true; pillars.push(pillar); }
    }

    // Birthplace pillars (b1-b4)
    if (chartData?.hs_b1 || chartData?.eb_b1) {
      const pillar = buildPillar('hs_b1', 'eb_b1', 'Birthplace 1') as any;
      if (pillar) { pillar.isLocation = true; pillar.isBirthplace = true; pillars.push(pillar); }
    }
    if (chartData?.hs_b2 || chartData?.eb_b2) {
      const pillar = buildPillar('hs_b2', 'eb_b2', 'Birthplace 2') as any;
      if (pillar) { pillar.isLocation = true; pillar.isBirthplace = true; pillars.push(pillar); }
    }
    if (chartData?.hs_b3 || chartData?.eb_b3) {
      const pillar = buildPillar('hs_b3', 'eb_b3', 'Birthplace 3') as any;
      if (pillar) { pillar.isLocation = true; pillar.isBirthplace = true; pillars.push(pillar); }
    }
    if (chartData?.hs_b4 || chartData?.eb_b4) {
      const pillar = buildPillar('hs_b4', 'eb_b4', 'Birthplace 4') as any;
      if (pillar) { pillar.isLocation = true; pillar.isBirthplace = true; pillars.push(pillar); }
    }

    return pillars;
  });

  // Filter pillars based on props
  let displayNatalPillars = $derived(showNatal ? natalPillars : []);
  let displayAlignedLuckPillars = $derived((showLuck || show10YrLuck) ? alignedLuckPillars : []);
  let displayTalismanPillars = $derived(showTalisman ? talismanPillars : []);
  let displayLocationPillars = $derived(showLocation ? locationPillars : []);

  // Calculate cumulative indices for proper ordering
  let luckOffset = $derived(displayNatalPillars.length);
  let talismanOffset = $derived(luckOffset + displayAlignedLuckPillars.length);
  let locationOffset = $derived(talismanOffset + displayTalismanPillars.length);

  // Check if any pillars to display
  let hasPillars = $derived(
    displayNatalPillars.length > 0 || displayAlignedLuckPillars.length > 0 ||
    displayTalismanPillars.length > 0 || displayLocationPillars.length > 0
  );

  // Dong Gong helpers
  let dongGong = $derived(chartData?.dong_gong);
  let dongGongRating = $derived(dongGong?.rating);
  let dongGongColor = $derived.by(() => {
    if (!dongGongRating) return 'var(--tui-fg)';
    const v = dongGongRating.value;
    if (v >= 4) return 'var(--tui-wood)';
    if (v === 3) return 'var(--tui-earth)';
    if (v === 2.5) return 'var(--tui-water)';
    if (v <= 1) return '#000000';
    return 'var(--tui-fire)';
  });
  let dongGongTitle = $derived.by(() => {
    if (!dongGong) return '';
    if (dongGong.forbidden) {
      return `\u8463\u516C: ${dongGong.forbidden.chinese} (${dongGong.forbidden.solar_term_chinese}) \u2014 ${dongGong.forbidden.english}`;
    }
    if (dongGong.consult?.promoted) {
      return `\u8463\u516C: ${dongGong.officer?.chinese || ''} \u8B70 (originally \u51F6) \u2014 ${dongGong.consult.reason}`;
    }
    return `\u8463\u516C: ${dongGong.officer?.chinese || ''} ${dongGongRating?.chinese || ''}`;
  });
</script>

{#if hasPillars}
  <div class="relative">
    <div class="relative w-full">
      <!-- Heavenly Stems Row -->
      <div class="flex gap-0 items-center flex-wrap">
        <!-- Natal Pillar Stems -->
        {#each displayNatalPillars as pillar, index (index)}
          <PillarCard
            {pillar}
            type="stem"
            index={index}
            {mappings}
            {hoveredInteractionId}
            onHoverInteraction={(id) => hoveredInteractionId = id}
          />
        {/each}

        <!-- Aligned Luck Pillar Stems -->
        {#each displayAlignedLuckPillars as pillar, index (index)}
          <PillarCard
            {pillar}
            type="stem"
            index={luckOffset + index}
            {mappings}
            isLuck={true}
            isEmpty={pillar.isEmpty}
            {hoveredInteractionId}
            onHoverInteraction={(id) => hoveredInteractionId = id}
          />
        {/each}

        <!-- Divider before location pillars -->
        {#if displayAlignedLuckPillars.length > 0 && displayLocationPillars.length > 0}
          <div class="luck-divider self-stretch bg-gradient-to-b from-transparent to-transparent opacity-70 {displayLocationPillars[0]?.isOverseas ? 'via-blue-500' : 'via-amber-500'}"></div>
        {/if}

        <!-- Location Pillar Stems -->
        {#each displayLocationPillars as pillar, index (index)}
          <PillarCard
            {pillar}
            type="stem"
            index={locationOffset + index}
            {mappings}
            isLocation={true}
            isOverseas={pillar.isOverseas}
            isBirthplace={pillar.isBirthplace}
            {hoveredInteractionId}
            onHoverInteraction={(id) => hoveredInteractionId = id}
          />
        {/each}

        <!-- Talisman Pillar Stems -->
        {#each displayTalismanPillars as pillar, index (index)}
          <PillarCard
            {pillar}
            type="stem"
            index={talismanOffset + index}
            {mappings}
            isTalisman={true}
            {hoveredInteractionId}
            onHoverInteraction={(id) => hoveredInteractionId = id}
          />
        {/each}
      </div>

      <!-- Dong Gong indicator row - between HS and EB on daily luck pillar -->
      {#if dongGongRating && displayAlignedLuckPillars.length > 0}
        <div class="flex gap-0 items-center">
          <!-- Empty spacers for natal pillars -->
          {#each displayNatalPillars as _, index (index)}
            <div class="w-28 flex-shrink-0"></div>
          {/each}
          <!-- Luck pillar columns - only daily (index 1) shows badge -->
          {#each displayAlignedLuckPillars as _, index (index)}
            <div class="w-28 flex-shrink-0 flex items-center justify-center">
              {#if index === 1}
                <span
                  class="text-xs font-medium px-1.5"
                  style="color: {dongGongColor};"
                  title={dongGongTitle}
                >
                  {dongGongRating.symbol} {dongGongRating.chinese}
                </span>
              {/if}
            </div>
          {/each}
        </div>
      {/if}

      <!-- Earthly Branches Row -->
      <div class="flex gap-0 overflow-visible items-stretch">
        <!-- Natal Pillar Branches -->
        {#each displayNatalPillars as pillar, index (index)}
          <PillarCard
            {pillar}
            type="branch"
            index={index}
            {mappings}
            {hoveredInteractionId}
            onHoverInteraction={(id) => hoveredInteractionId = id}
          />
        {/each}

        <!-- Aligned Luck Pillar Branches -->
        {#each displayAlignedLuckPillars as pillar, index (index)}
          <PillarCard
            {pillar}
            type="branch"
            index={luckOffset + index}
            {mappings}
            isLuck={true}
            isEmpty={pillar.isEmpty}
            {hoveredInteractionId}
            onHoverInteraction={(id) => hoveredInteractionId = id}
          />
        {/each}

        <!-- Divider before location pillars -->
        {#if displayAlignedLuckPillars.length > 0 && displayLocationPillars.length > 0}
          <div class="luck-divider self-stretch bg-gradient-to-b from-transparent to-transparent opacity-70 {displayLocationPillars[0]?.isOverseas ? 'via-blue-500' : 'via-amber-500'}"></div>
        {/if}

        <!-- Location Pillar Branches -->
        {#each displayLocationPillars as pillar, index (index)}
          <PillarCard
            {pillar}
            type="branch"
            index={locationOffset + index}
            {mappings}
            isLocation={true}
            isOverseas={pillar.isOverseas}
            isBirthplace={pillar.isBirthplace}
            {hoveredInteractionId}
            onHoverInteraction={(id) => hoveredInteractionId = id}
          />
        {/each}

        <!-- Talisman Pillar Branches -->
        {#each displayTalismanPillars as pillar, index (index)}
          <PillarCard
            {pillar}
            type="branch"
            index={talismanOffset + index}
            {mappings}
            isTalisman={true}
            {hoveredInteractionId}
            onHoverInteraction={(id) => hoveredInteractionId = id}
          />
        {/each}
      </div>
    </div>
  </div>
{/if}
