// src/components/InlineLifeEventForm.tsx
'use client';

import React, { useState, useCallback, useRef, useEffect } from 'react';
import { createLifeEvent, type LifeEventCreate, type LifeEvent } from '@/lib/api';
import { useT } from './LanguageProvider';
import { ACTIONS, EVENT_FORM, LOCATION, PROFILE_FORM } from '@/lib/t';

interface InlineLifeEventFormProps {
  profileId: string;
  onSuccess?: (event: LifeEvent) => void;
  onCancel?: () => void;
  existingDates?: { year: number; month?: number | null; day?: number | null }[];
  className?: string;
}

export default function InlineLifeEventForm({
  profileId,
  onSuccess,
  onCancel,
  existingDates = [],
  className = '',
}: InlineLifeEventFormProps) {
  const { t, tCompact } = useT();
  const currentYear = new Date().getFullYear();

  // Form state
  const [year, setYear] = useState<number | string>(currentYear.toString());
  const [month, setMonth] = useState<number | string>('');
  const [day, setDay] = useState<number | string>('');
  const [location, setLocation] = useState('');
  const [isAbroad, setIsAbroad] = useState(false);
  const [notes, setNotes] = useState('');

  // UI state
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Refs
  const yearRef = useRef<HTMLInputElement>(null);
  const monthRef = useRef<HTMLInputElement>(null);
  const dayRef = useRef<HTMLInputElement>(null);
  const locationRef = useRef<HTMLInputElement>(null);

  // Auto-focus year on mount
  useEffect(() => {
    yearRef.current?.focus();
  }, []);

  // Validation
  const yearNum = typeof year === 'string' ? parseInt(year, 10) : year;
  const monthNum = typeof month === 'string' && month !== '' ? parseInt(month, 10) : null;
  const dayNum = typeof day === 'string' && day !== '' ? parseInt(day, 10) : null;

  const isValidYear = !isNaN(yearNum) && yearNum >= 1900 && yearNum <= 2100;
  const isValid = isValidYear;

  // Check for duplicate
  const isDuplicate = existingDates.some(d =>
    d.year === yearNum &&
    (d.month || null) === monthNum &&
    (d.day || null) === dayNum
  );

  // Handle form submission
  const handleSubmit = useCallback(async () => {
    setError(null);

    if (!isValidYear) {
      setError(t(EVENT_FORM.valid_year));
      return;
    }

    if (isDuplicate) {
      setError(t(EVENT_FORM.duplicate));
      return;
    }

    if (dayNum && !monthNum) {
      setError(t(EVENT_FORM.specify_month));
      return;
    }

    setIsSubmitting(true);

    try {
      const eventData: LifeEventCreate = {
        year: yearNum,
        month: monthNum,
        day: dayNum,
        location: location.trim() || null,
        notes: notes.trim() || null,
        is_abroad: location.trim() ? isAbroad : false,
      };

      const newEvent = await createLifeEvent(profileId, eventData);
      onSuccess?.(newEvent);
    } catch (err) {
      setError(err instanceof Error ? err.message : t(EVENT_FORM.failed_create));
    } finally {
      setIsSubmitting(false);
    }
  }, [isValidYear, isDuplicate, yearNum, monthNum, dayNum, location, notes, profileId, onSuccess]);

  // Handle month input
  const handleMonthChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    if (!/^\d*$/.test(value) || value.length > 2) return;

    const num = parseInt(value, 10);
    if (num > 12) return;

    setMonth(value);

    // Auto-advance: 2 digits OR single digit > 1
    if (value.length === 2 || (value.length === 1 && num > 1)) {
      setTimeout(() => dayRef.current?.focus(), 0);
    }
  }, []);

  // Handle day input
  const handleDayChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    if (!/^\d*$/.test(value) || value.length > 2) return;

    const num = parseInt(value, 10);
    if (num > 31) return;

    setDay(value);

    // Auto-advance: 2 digits
    if (value.length === 2) {
      setTimeout(() => locationRef.current?.focus(), 0);
    }
  }, []);

  // Handle year completion
  const handleYearComplete = useCallback(() => {
    setTimeout(() => monthRef.current?.focus(), 0);
  }, []);

  // Handle backspace for navigation
  const handleFieldKeyDown = useCallback((
    e: React.KeyboardEvent<HTMLInputElement>,
    currentRef: React.RefObject<HTMLInputElement | null>,
    prevRef?: React.RefObject<HTMLInputElement | null>
  ) => {
    if (e.key === 'Backspace' && currentRef.current?.value === '' && prevRef) {
      e.preventDefault();
      prevRef.current?.focus();
    }
  }, []);

  // Keyboard handling for the form wrapper
  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    // Enter to submit (only if not in a textarea)
    if (e.key === 'Enter' && !e.shiftKey) {
      const target = e.target as HTMLElement;
      if (target.tagName !== 'TEXTAREA') {
        e.preventDefault();
        if (isValid && !isDuplicate && !isSubmitting) {
          handleSubmit();
        }
      }
    }

    // Escape to cancel
    if (e.key === 'Escape' && onCancel) {
      e.preventDefault();
      onCancel();
    }
  }, [isValid, isDuplicate, isSubmitting, handleSubmit, onCancel]);

  return (
    <div className={`tui-frame ${className}`} onKeyDown={handleKeyDown}>
      <div className="tui-frame-title">{t(EVENT_FORM.add_title)}</div>
      <table className="tui-table-form">
        <tbody>
          <tr>
            <td>{t(EVENT_FORM.date)}*</td>
            <td>
              <div className="guided-date-input">
                <input
                  ref={yearRef}
                  type="text"
                  inputMode="numeric"
                  pattern="[0-9]*"
                  value={year}
                  onChange={(e) => {
                    const value = e.target.value;
                    if (!/^\d*$/.test(value) || value.length > 4) return;
                    setYear(value);
                    if (value.length === 4) {
                      const num = parseInt(value, 10);
                      if (num >= 1900 && num <= 2100) {
                        handleYearComplete();
                      }
                    }
                  }}
                  placeholder="YYYY"
                  disabled={isSubmitting}
                  className="guided-input-segment guided-input-year tui-input"
                  style={!isValidYear && year !== '' ? { borderColor: 'var(--tui-error)' } : {}}
                  aria-label="Year"
                  autoComplete="off"
                />
                <span className="guided-input-separator">/</span>
                <input
                  ref={monthRef}
                  type="text"
                  inputMode="numeric"
                  pattern="[0-9]*"
                  value={month}
                  onChange={handleMonthChange}
                  onKeyDown={(e) => handleFieldKeyDown(e, monthRef, yearRef)}
                  placeholder="MM"
                  disabled={isSubmitting}
                  className="guided-input-segment guided-input-month tui-input"
                  aria-label="Month (optional)"
                  autoComplete="off"
                />
                <span className="guided-input-separator">/</span>
                <input
                  ref={dayRef}
                  type="text"
                  inputMode="numeric"
                  pattern="[0-9]*"
                  value={day}
                  onChange={handleDayChange}
                  onKeyDown={(e) => handleFieldKeyDown(e, dayRef, monthRef)}
                  placeholder="DD"
                  disabled={isSubmitting || !monthNum}
                  className="guided-input-segment guided-input-day tui-input"
                  style={!monthNum ? { opacity: 0.5 } : {}}
                  aria-label="Day (optional)"
                  autoComplete="off"
                />
              </div>
              <div style={{ fontSize: '0.625rem', color: 'var(--tui-fg-muted)', marginTop: '0.125rem' }}>
                {t(EVENT_FORM.year_required)}
              </div>
            </td>
          </tr>
          <tr>
            <td>{t(EVENT_FORM.location)}</td>
            <td>
              <input
                ref={locationRef}
                type="text"
                value={location}
                onChange={(e) => setLocation(e.target.value)}
                placeholder={t(EVENT_FORM.where_happened)}
                maxLength={200}
                disabled={isSubmitting}
                autoComplete="off"
              />
              {location.trim() && (
                <div style={{ marginTop: '0.25rem' }}>
                  <button
                    type="button"
                    onClick={() => setIsAbroad(!isAbroad)}
                    disabled={isSubmitting}
                    className="inline-flex items-center gap-1 px-1.5 py-0.5 text-xs transition-colors"
                    style={{
                      color: isAbroad ? 'var(--tui-water)' : 'var(--tui-fg-muted)',
                      background: isAbroad ? 'color-mix(in srgb, var(--tui-water) 15%, var(--tui-bg))' : 'transparent',
                      border: `1px solid ${isAbroad ? 'var(--tui-water)' : 'var(--tui-border)'}`,
                    }}
                    title={t(LOCATION.abroad_hint)}
                  >
                    <span style={{ fontFamily: 'monospace' }}>{isAbroad ? '[x]' : '[_]'}</span>
                    <span>{tCompact(LOCATION.abroad)}</span>
                  </button>
                </div>
              )}
            </td>
          </tr>
          <tr>
            <td>{t(EVENT_FORM.notes)}</td>
            <td>
              <textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder={t(EVENT_FORM.what_happened)}
                className="resize-none"
                rows={2}
                maxLength={10000}
                disabled={isSubmitting}
              />
            </td>
          </tr>
        </tbody>
      </table>
      {isDuplicate && (
        <div className="tui-form-error" role="alert">{t(EVENT_FORM.duplicate)}</div>
      )}
      {error && <div className="tui-form-error" role="alert">{error}</div>}
      <div className="tui-form-actions">
        {onCancel && (
          <button type="button" onClick={onCancel} className="tui-btn" disabled={isSubmitting}>
            {tCompact(ACTIONS.cancel)}
          </button>
        )}
        <button
          type="button"
          onClick={handleSubmit}
          className="tui-btn"
          disabled={!isValid || isDuplicate || isSubmitting}
        >
          {isSubmitting ? '...' : tCompact(ACTIONS.add)}
        </button>
      </div>
    </div>
  );
}

// src/components/InlineLifeEventForm.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import type { LifeEventCreate, LifeEvent } from '$lib/api.types';
	import { createLifeEvent } from '$lib/api';

	interface Props {
		profileId: string;
		onSuccess?: (event: LifeEvent) => void;
		onCancel?: () => void;
		existingDates?: { year: number; month?: number | null; day?: number | null }[];
		class?: string;
	}

	let {
		profileId,
		onSuccess,
		onCancel,
		existingDates = [],
		class: className = ''
	}: Props = $props();

	const currentYear = new Date().getFullYear();

	// Form state
	let year: number | string = $state(currentYear.toString());
	let month: number | string = $state('');
	let day: number | string = $state('');
	let location = $state('');
	let isAbroad = $state(false);
	let notes = $state('');

	// UI state
	let error: string | null = $state(null);
	let isSubmitting = $state(false);

	// Element refs
	let yearEl: HTMLInputElement | undefined = $state(undefined);
	let monthEl: HTMLInputElement | undefined = $state(undefined);
	let dayEl: HTMLInputElement | undefined = $state(undefined);
	let locationEl: HTMLInputElement | undefined = $state(undefined);

	// Auto-focus year on mount
	onMount(() => {
		yearEl?.focus();
	});

	// Derived validation
	let yearNum = $derived(typeof year === 'string' ? parseInt(year, 10) : year);
	let monthNum = $derived(typeof month === 'string' && month !== '' ? parseInt(month, 10) : null);
	let dayNum = $derived(typeof day === 'string' && day !== '' ? parseInt(day, 10) : null);

	let isValidYear = $derived(!isNaN(yearNum) && yearNum >= 1900 && yearNum <= 2100);
	let isValid = $derived(isValidYear);

	// Check for duplicate
	let isDuplicate = $derived(
		existingDates.some(
			(d) =>
				d.year === yearNum &&
				(d.month || null) === monthNum &&
				(d.day || null) === dayNum
		)
	);

	// Handle form submission
	async function handleSubmit() {
		error = null;

		if (!isValidYear) {
			error = 'Please enter a valid year (1900-2100)';
			return;
		}

		if (isDuplicate) {
			error = 'An event with this date already exists';
			return;
		}

		if (dayNum && !monthNum) {
			error = 'Please specify the month if you know the day';
			return;
		}

		isSubmitting = true;

		try {
			const eventData: LifeEventCreate = {
				year: yearNum,
				month: monthNum,
				day: dayNum,
				location: location.trim() || null,
				notes: notes.trim() || null,
				is_abroad: location.trim() ? isAbroad : false
			};

			const newEvent = await createLifeEvent(profileId, eventData);
			onSuccess?.(newEvent);
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to create event';
		} finally {
			isSubmitting = false;
		}
	}

	// Handle year input
	function handleYearInput(e: Event) {
		const value = (e.target as HTMLInputElement).value;
		if (!/^\d*$/.test(value) || value.length > 4) return;
		year = value;

		if (value.length === 4) {
			const num = parseInt(value, 10);
			if (num >= 1900 && num <= 2100) {
				setTimeout(() => monthEl?.focus(), 0);
			}
		}
	}

	// Handle month input
	function handleMonthInput(e: Event) {
		const value = (e.target as HTMLInputElement).value;
		if (!/^\d*$/.test(value) || value.length > 2) return;

		const num = parseInt(value, 10);
		if (num > 12) return;

		month = value;

		// Auto-advance: 2 digits OR single digit > 1
		if (value.length === 2 || (value.length === 1 && num > 1)) {
			setTimeout(() => dayEl?.focus(), 0);
		}
	}

	// Handle day input
	function handleDayInput(e: Event) {
		const value = (e.target as HTMLInputElement).value;
		if (!/^\d*$/.test(value) || value.length > 2) return;

		const num = parseInt(value, 10);
		if (num > 31) return;

		day = value;

		// Auto-advance: 2 digits
		if (value.length === 2) {
			setTimeout(() => locationEl?.focus(), 0);
		}
	}

	// Handle backspace for navigation between fields
	function handleMonthKeyDown(e: KeyboardEvent) {
		if (e.key === 'Backspace' && monthEl?.value === '') {
			e.preventDefault();
			yearEl?.focus();
		}
	}

	function handleDayKeyDown(e: KeyboardEvent) {
		if (e.key === 'Backspace' && dayEl?.value === '') {
			e.preventDefault();
			monthEl?.focus();
		}
	}

	// Handle location input
	function handleLocationInput(e: Event) {
		location = (e.target as HTMLInputElement).value;
	}

	// Handle notes input
	function handleNotesInput(e: Event) {
		notes = (e.target as HTMLTextAreaElement).value;
	}

	// Keyboard handling for the form wrapper
	function handleKeyDown(e: KeyboardEvent) {
		// Enter to submit (only if not in a textarea)
		if (e.key === 'Enter' && !e.shiftKey) {
			const target = e.target as HTMLElement;
			if (target.tagName !== 'TEXTAREA') {
				e.preventDefault();
				if (isValid && !isDuplicate && !isSubmitting) {
					handleSubmit();
				}
			}
		}

		// Escape to cancel
		if (e.key === 'Escape' && onCancel) {
			e.preventDefault();
			onCancel();
		}
	}

	let yearErrorStyle = $derived(
		!isValidYear && year !== '' ? 'border-color: var(--tui-error)' : ''
	);
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="tui-frame {className}" onkeydown={handleKeyDown}>
	<div class="tui-frame-title">Add Life Event</div>
	<table class="tui-table-form">
		<tbody>
			<tr>
				<td>Date*</td>
				<td>
					<div class="guided-date-input">
						<input
							bind:this={yearEl}
							type="text"
							inputmode="numeric"
							pattern="[0-9]*"
							value={year}
							oninput={handleYearInput}
							placeholder="YYYY"
							disabled={isSubmitting}
							class="guided-input-segment guided-input-year tui-input"
							style={yearErrorStyle}
							aria-label="Year"
							autocomplete="off"
						/>
						<span class="guided-input-separator">/</span>
						<input
							bind:this={monthEl}
							type="text"
							inputmode="numeric"
							pattern="[0-9]*"
							value={month}
							oninput={handleMonthInput}
							onkeydown={handleMonthKeyDown}
							placeholder="MM"
							disabled={isSubmitting}
							class="guided-input-segment guided-input-month tui-input"
							aria-label="Month (optional)"
							autocomplete="off"
						/>
						<span class="guided-input-separator">/</span>
						<input
							bind:this={dayEl}
							type="text"
							inputmode="numeric"
							pattern="[0-9]*"
							value={day}
							oninput={handleDayInput}
							onkeydown={handleDayKeyDown}
							placeholder="DD"
							disabled={isSubmitting || !monthNum}
							class="guided-input-segment guided-input-day tui-input"
							style={!monthNum ? 'opacity: 0.5' : ''}
							aria-label="Day (optional)"
							autocomplete="off"
						/>
					</div>
					<div class="date-hint">
						Year required; month and day optional
					</div>
				</td>
			</tr>
			<tr>
				<td>Location</td>
				<td>
					<input
						bind:this={locationEl}
						type="text"
						value={location}
						oninput={handleLocationInput}
						placeholder="Where did it happen?"
						maxlength={200}
						disabled={isSubmitting}
						autocomplete="off"
					/>
					{#if location.trim()}
						<div class="abroad-toggle-row">
							<button
								type="button"
								onclick={() => { isAbroad = !isAbroad; }}
								disabled={isSubmitting}
								class="abroad-toggle"
								style="
									color: {isAbroad ? 'var(--tui-water)' : 'var(--tui-fg-muted)'};
									background: {isAbroad ? 'color-mix(in srgb, var(--tui-water) 15%, var(--tui-bg))' : 'transparent'};
									border-color: {isAbroad ? 'var(--tui-water)' : 'var(--tui-border)'}
								"
								title="Was this event abroad (outside birth country)?"
							>
								<span class="abroad-checkbox">{isAbroad ? '[x]' : '[_]'}</span>
								<span>Abroad</span>
							</button>
						</div>
					{/if}
				</td>
			</tr>
			<tr>
				<td>Notes</td>
				<td>
					<textarea
						value={notes}
						oninput={handleNotesInput}
						placeholder="What happened?"
						class="notes-textarea"
						rows={2}
						maxlength={10000}
						disabled={isSubmitting}
					></textarea>
				</td>
			</tr>
		</tbody>
	</table>

	{#if isDuplicate}
		<div class="tui-form-error" role="alert">An event with this date already exists</div>
	{/if}

	{#if error}
		<div class="tui-form-error" role="alert">{error}</div>
	{/if}

	<div class="tui-form-actions">
		{#if onCancel}
			<button type="button" onclick={onCancel} class="tui-btn" disabled={isSubmitting}>
				Cancel
			</button>
		{/if}
		<button
			type="button"
			onclick={handleSubmit}
			class="tui-btn"
			disabled={!isValid || isDuplicate || isSubmitting}
		>
			{isSubmitting ? '...' : 'Add'}
		</button>
	</div>
</div>

<style>
	.date-hint {
		font-size: 0.625rem;
		color: var(--tui-fg-muted);
		margin-top: 0.125rem;
	}

	.abroad-toggle-row {
		margin-top: 0.25rem;
	}

	.abroad-toggle {
		display: inline-flex;
		align-items: center;
		gap: 0.25rem;
		padding: 0.125rem 0.375rem;
		font-size: 0.75rem;
		border: 1px solid;
		cursor: pointer;
		transition: color 0.15s, background 0.15s, border-color 0.15s;
	}

	.abroad-checkbox {
		font-family: monospace;
	}

	.notes-textarea {
		resize: none;
		width: 100%;
	}
</style>
