// src/components/NarrativeDisplay.svelte
<script lang="ts">
  import NarrativeCard from './NarrativeCard.svelte';

  interface NarrativeDisplayProps {
    chartData: any;
  }

  let { chartData }: NarrativeDisplayProps = $props();

  let narrativeAnalysis = $derived(chartData?.narrative_analysis);
  let chronological = $derived(narrativeAnalysis?.all_chronological);
  let hasData = $derived(narrativeAnalysis && chronological && chronological.length > 0);
</script>

{#if hasData}
  <div class="narrative-panel">
    <div class="narrative-panel-inner">
      <div class="space-y-1.5">
        {#each chronological as entry (entry.seq)}
          <NarrativeCard
            narrative={entry}
            mappings={chartData?.mappings}
          />
        {/each}
      </div>
      <div class="mt-2 text-[9px] tui-text-dim font-mono text-right">
        {chronological.length} interactions
      </div>
    </div>
  </div>
{/if}

// src/components/NarrativeDisplay.tsx
'use client';

import NarrativeCard from './NarrativeCard';

interface NarrativeDisplayProps {
  chartData: any;
}

export default function NarrativeDisplay({ chartData }: NarrativeDisplayProps) {
  const narrativeAnalysis = chartData?.narrative_analysis;
  const chronological = narrativeAnalysis?.all_chronological;

  if (!narrativeAnalysis || !chronological || chronological.length === 0) {
    return null;
  }

  return (
    <div className="narrative-panel">
      <div className="narrative-panel-inner">
        <div className="space-y-1.5">
          {chronological.map((entry: any) => (
            <NarrativeCard
              key={`chrono-${entry.seq}`}
              narrative={entry}
              mappings={chartData?.mappings}
            />
          ))}
        </div>
        <div className="mt-2 text-[9px] tui-text-dim font-mono text-right">
          {chronological.length} interactions (chronological)
        </div>
      </div>
    </div>
  );
}
