// src/app/calendar/page.tsx
'use client';

import Header from '@/components/Header';
import DongGongCalendar from '@/components/DongGongCalendar';

export default function CalendarPage() {
  return (
    <div className="min-h-screen tui-bg">
      <Header />
      <main className="mx-auto main-content px-4 py-4">
        <div className="mx-auto" style={{ maxWidth: '800px' }}>
          <DongGongCalendar />
        </div>
      </main>
    </div>
  );
}

// src/routes/calendar/+page.svelte
<script lang="ts">
  import Header from '../../components/Header.svelte';
  import DongGongCalendar from '../../components/DongGongCalendar.svelte';
</script>

<div class="min-h-screen tui-bg">
  <Header />
  <main class="mx-auto main-content px-4 py-4">
    <div class="mx-auto" style="max-width: 800px;">
      <DongGongCalendar />
    </div>
  </main>
</div>
